project:
  type: website
  output-dir: docs

website:
  title: "Μαθηματικά Γυμνασίου & Λυκείου"

  navbar:
    left:
      - text: Γυμνάσιο
        menu:
          - text: Α Τάξη
            href: gymnasio/a/index.qmd
          - text: Β Τάξη
            href: gymnasio/b/index.qmd
          - text: Γ Τάξη
            href: gymnasio/g/index.qmd
      - text: Λύκειο
        menu:
          - text: Α Τάξη
            href: lykeio/a/index.qmd
          - text: Β Τάξη
            href: lykeio/b/index.qmd
          - text: Γ Τάξη
            href: lykeio/g/index.qmd

  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - about.qmd
      - Πίνακας Τριγωνομετρικών Αριθμών.qmd
      - section: "Γυμνάσιο"
        contents:
          - section: "Α' Γυμνασίου – Μαθηματικά"
            href: gymnasio/a/index.qmd
            contents:
              - section: "Αλγεβρα"
                contents:
                  - auto: "gymnasio/a/algebra/*"
              - section: "Γεωμετρία"
                contents:
                  - auto: "gymnasio/a/geometria/*"    
          - section: "Β' Γυμνασίου – Μαθηματικά"
            href: gymnasio/b/index.qmd
            contents:
              - section: "Αλγεβρα"
                contents:
                  - auto: "gymnasio/b/algebra/*"
              - section: "Γεωμετρία"
                contents:
                  - auto: "gymnasio/b/geometria/*"
          - section: "Γ' Γυμνασίου – Μαθηματικά"
            href: gymnasio/g/index.qmd
            contents:
              - section: "Αλγεβρα"
                contents:
                  - auto: "gymnasio/g/algebra/*"
              - section: "Γεωμετρία"
                contents:
                  - auto: "gymnasio/g/geometria/*"
      - section: "Λύκειο"
        contents:
          - section: "Α' Λυκείου – Μαθηματικά"
            href: lykeio/a/index.qmd
            contents:
              - section: "Άλγεβρα"
                contents:
                  - auto: "lykeio/a/algebra/*"
              - section: "Γεωμετρία"
                contents:
                  - auto: "lykeio/a/geometria/*"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 5
    number-sections: true
    css: styles.css