---
title: "07. Ισοδύναμα κλάσματα"
author: "ΤΑΣΟΣ ΑΡΒΑΝΙΤΗΣ"
format:
  html:
    title-block-banner: true

page-layout: full
body-classes: page-agalgebra

lang: el
date: "07/17/2026"
date-modified: today
date-format: "D MMMM YYYY"

header-includes:
 - |
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        TeX: { extensions: ["AMSmath.js", "AMSsymbols.js", "color.js", "bbox.js"] }
editor_options: 
  markdown: 
    wrap: sentence
---

------------------------------------------------------------------------

## Ισοδύναμα κλάσματα

### Έννοια των ισοδύναμων κλασμάτων

::: {style="background-color: #b5b1de; border: 2px solid #2f3e50; color: #25188a; padding: 15px; border-radius: 5px;"}

**Θεωρία και Ορισμοί**

*   **Ορισμός:** Δύο κλάσματα $\dfrac{\alpha}{\beta}$ και $\dfrac{\gamma}{\delta}$ ονομάζονται **ισοδύναμα ή ίσα**, όταν **εκφράζουν το ίδιο μέρος ενός μεγέθους** ή ίσων μεγεθών.

*   **Θεμελιώδης αρχή:** Αν και οι δύο όροι ενός κλάσματος πολλαπλασιαστούν ή διαιρεθούν με τον ίδιο φυσικό αριθμό (διάφορο του μηδενός), προκύπτει κλάσμα ισοδύναμο με το αρχικό.

$$\dfrac{\alpha}{\beta} = \dfrac{κ\cdot α}{κ\cdot β}$$
και 

$$\dfrac{\alpha}{\beta} = \dfrac{ α : λ}{ β : λ}$$

**Ιδιότητες**

*   Κάθε κλάσμα αποτελεί μέλος μιας **κλάσης ισοδυναμίας**, η οποία περιέχει άπειρα κλάσματα που εκφράζουν την ίδια τιμή.

$$\dfrac{\alpha}{\beta} = \dfrac{2\cdot α}{2\cdot β}= \dfrac{3\cdot α}{3\cdot β}= \dfrac{4\cdot α}{4\cdot β}= \dfrac{5\cdot α}{5\cdot β}= \dfrac{6\cdot α}{6\cdot β}= \dfrac{7\cdot α}{7\cdot β} = \cdots$$

*   Ισχύουν οι ιδιότητες της ισότητας: 

**ανακλαστική** ($\dfrac{\alpha}{\beta} = \dfrac{\alpha}{\beta}$), 

**συμμετρική** (αν $\dfrac{\alpha}{\beta} = \dfrac{\gamma}{\delta}$ τότε $\dfrac{\gamma}{\delta} = \dfrac{\alpha}{\beta}$) και 

**μεταβατική**.

$$
Άν \ \  \ 
\begin{cases}
\dfrac{\alpha}{\beta} = \dfrac{\gamma}{\delta}\\
\dfrac{γ}{δ} = \dfrac{ζ}{η}
\end{cases}
\Rightarrow \dfrac{\alpha}{\beta} = \dfrac{ζ}{η}
$$

:::

**Παραδείγματα**

1.  $\dfrac{1}{3} = \dfrac{1 \cdot 4}{3 \cdot 4} = \dfrac{4}{12}$.
2.  $\dfrac{8}{4} = \dfrac{4}{2}$ (διαίρεση με το 2) ***Απλοποίηση***.
3.  $\dfrac{2}{3} = \dfrac{10}{15}$ (πολλαπλασιασμός με το 5).
4.  $\dfrac{10}{15} = \dfrac{2}{3}$ (διαίρεση με το 5). ***Απλοποίηση***
5.  $\dfrac{3}{5} = \dfrac{60}{100}$ (πολλαπλασιασμός με το 20).

**Ασκήσεις**

1.  Βρείτε ένα ισοδύναμο κλάσμα του $\dfrac{3}{5}$ με παρονομαστή 100.
2.  Εξετάστε αν τα κλάσματα $\dfrac{2}{3}$ και $\dfrac{18}{27}$ είναι ισοδύναμα.
3.  Μετατρέψτε το $\dfrac{2}{3}$ σε ισοδύναμο με παρονομαστή 6.
4.  Μετατρέψτε το $\dfrac{2}{3}$ σε ισοδύναμο με παρονομαστή 15.
5.  Συμπληρώστε το κενό: $\dfrac{2}{3} = \dfrac{22}{\dots}$.
6.  Συμπληρώστε το κενό: $\dfrac{\dots}{5} = \dfrac{9}{15}$.
7.  Συμπληρώστε το κενό: $\dfrac{14}{4} = \dfrac{\dots}{20}$.
8.  Συμπληρώστε το κενό: $\dfrac{48}{36} = \dfrac{\dots}{24}$.
9.  Γράψτε το $\dfrac{3}{4}$ ως ισοδύναμο με παρονομαστή 100.
10. Γράψτε το $\dfrac{8}{5}$ ως ισοδύναμο με παρονομαστή 100.
11. Γράψτε το $\dfrac{5}{2}$ ως ισοδύναμο με παρονομαστή 100.
12. Βρείτε το σύνολο των κλασμάτων ισοδυνάμων με το $\dfrac{2}{3}$ που έχουν αριθμητή $21 \leq \alpha \leq 55$.




------------------------------------------------------------------------

### Απλοποίηση κλασμάτων

::: {style="background-color: #b5b1de; border: 2px solid #2f3e50; color: #25188a; padding: 15px; border-radius: 5px;"}

**Θεωρία και Ορισμοί**

*   **Ορισμός:** **Απλοποίηση** είναι η διαδικασία κατά την οποία **διαιρούμε και τους δύο όρους ενός κλάσματος με έναν κοινό διαιρέτη** τους.

$$\dfrac{18}{30}=\dfrac{18:2}{30:2}=\dfrac{9}{15}= \dfrac{9:3}{15:3}=\dfrac{3}{5} \ \ \  \textbf{   Ανάγωγο}$$

*   **Ανάγωγο κλάσμα:** Το κλάσμα που **δεν μπορεί να απλοποιηθεί περισσότερο**, επειδή ο αριθμητής και ο παρονομαστής του είναι αριθμοί πρώτοι μεταξύ τους ($ΜΚΔ=1$).

**Ιδιότητες**

*   Για να μετατρέψουμε ένα κλάσμα απευθείας στο ισοδύναμο ανάγωγό του, διαιρούμε τους όρους του με τον **Μέγιστο Κοινό Διαιρέτη (ΜΚΔ)** τους.

*   Αν ένας από τους όρους είναι 1, το κλάσμα είναι πάντα ανάγωγο.

:::

**Παραδείγματα**

1.  $\dfrac{24}{36} = \dfrac{24:12}{36:12} = \dfrac{2}{3}$ (το $\dfrac{2}{3}$ είναι ανάγωγο).
2.  $\dfrac{18}{48} = \dfrac{18:6}{48:6} = \dfrac{3}{8}$.
3.  $\dfrac{30}{66} = \dfrac{30:6}{66:6} = \dfrac{5}{11}$.
4.  $\dfrac{25}{30} = \dfrac{25:5}{30:5} = \dfrac{5}{6}$.
5.  $\dfrac{12}{9} = \dfrac{12:3}{9:3} = \dfrac{4}{3}$.

**Ασκήσεις**

1.  Απλοποιήστε το κλάσμα $\dfrac{14}{42}$.
2.  Απλοποιήστε το κλάσμα $\dfrac{144}{96}$.
3.  Εξετάστε αν το $\dfrac{39}{40}$ είναι ανάγωγο.
4.  Απλοποιήστε το κλάσμα $\dfrac{225}{315}$.
5.  Απλοποιήστε το κλάσμα $\dfrac{32}{56}$.
6.  Ελέγξτε αν το $\dfrac{32}{30}$ είναι ανάγωγο.
7.  Ελέγξτε αν το $\dfrac{15}{14}$ είναι ανάγωγο.
8.  Ελέγξτε αν το $\dfrac{51}{16}$ είναι ανάγωγο.
9.  Ελέγξτε αν το $\dfrac{26}{50}$ είναι ανάγωγο.
10. Απλοποιήστε το κλάσμα $\dfrac{16}{60}$.
11. Απλοποιήστε το κλάσμα $\dfrac{72}{108}$.
12. Απλοποιήστε το κλάσμα $\dfrac{55}{66}$.

---


### 3. Μετατροπή κλασμάτων σε ομώνυμα


::: {style="background-color: #b5b1de; border: 2px solid #2f3e50; color: #25188a; padding: 15px; border-radius: 5px;"}

**Θεωρία και Ορισμοί**

 *   **Ορισμοί:** Τα κλάσματα που έχουν τον **ίδιο παρονομαστή** λέγονται **ομώνυμα**, ενώ εκείνα με διαφορετικό παρονομαστή λέγονται **ετερώνυμα**.

*   **Σκοπός:** Η μετατροπή σε ομώνυμα είναι απαραίτητη για τη **σύγκριση**, την **πρόσθεση** και την **αφαίρεση** ετερωνύμων κλασμάτων.

**Ιδιότητες και Μέθοδος**

1.  Ελέγχουμε αν τα κλάσματα απλοποιούνται.
2.  Βρίσκουμε το **Ελάχιστο Κοινό Πολλαπλάσιο (ΕΚΠ)** των παρονομαστών.
3.  Διαιρούμε το ΕΚΠ με κάθε παρονομαστή για να βρούμε τους «πολλαπλασιαστές».
4.  Πολλαπλασιάζουμε τους όρους κάθε κλάσματος με τον αντίστοιχο αριθμό.

:::

**Παραδείγματα**

1.  Τα $\dfrac{3}{5}, \dfrac{2}{3}, \dfrac{1}{4}$ γίνονται $\dfrac{36}{60}, \dfrac{40}{60}, \dfrac{15}{60}$ ($ΕΚΠ=60$).
2.  Τα $\dfrac{5}{6}, \dfrac{11}{9}$ γίνονται $\dfrac{15}{18}, \dfrac{22}{18}$ ($ΕΚΠ=18$).
3.  Τα $\dfrac{5}{6}, \dfrac{7}{8}$ γίνονται $\dfrac{20}{24}, \dfrac{21}{24}$ ($ΕΚΠ=24$).
4.  Τα $\dfrac{2}{3}, \dfrac{7}{4}$ γίνονται $\dfrac{8}{12}, \dfrac{21}{12}$ ($ΕΚΠ=12$).
5.  Τα $\dfrac{3}{4}, \dfrac{5}{6}$ γίνονται $\dfrac{9}{12}, \dfrac{10}{12}$ ($ΕΚΠ=12$).

**Ασκήσεις**

1.  Κάντε ομώνυμα τα κλάσματα $\dfrac{3}{5}$ και $\dfrac{7}{9}$.
2.  Κάντε ομώνυμα τα κλάσματα $\dfrac{7}{8}$ και $\dfrac{3}{10}$.
3.  Κάντε ομώνυμα τα κλάσματα $\dfrac{11}{3}$ και $\dfrac{7}{12}$.
4.  Κάντε ομώνυμα τα $\dfrac{5}{12}, \dfrac{7}{18}, \dfrac{11}{24}$.
5.  Κάντε ομώνυμα τα $\dfrac{7}{5}, \dfrac{9}{12}, \dfrac{21}{15}, \dfrac{17}{30}$.
6.  Μετατρέψτε τα $\dfrac{1}{3}, \dfrac{3}{6}, \dfrac{5}{8}, \dfrac{7}{12}$ σε κλάσματα με παρονομαστή 24.
7.  Να γίνουν ομώνυμα τα $\dfrac{5}{6}, \dfrac{3}{8}, \dfrac{1}{2}, \dfrac{2}{3}$.
8.  Να γίνουν ομώνυμα τα $\dfrac{11}{2}, \dfrac{7}{16}, \dfrac{3}{8}$.
9.  Να γίνουν ομώνυμα τα $\dfrac{3}{5}, \dfrac{5}{6}, \dfrac{1}{2}, \dfrac{2}{3}$.
10. Κάντε ομώνυμα τα $\dfrac{6}{8}, \dfrac{5}{10}, \dfrac{6}{18}$.
11. Κάντε ομώνυμα τα $\dfrac{3}{15}, \dfrac{4}{16}, \dfrac{5}{24}$.
12. Κάντε ομώνυμα τα $\dfrac{3}{10}, \dfrac{5}{100}, \dfrac{18}{27}, \dfrac{19}{1000}$.





------------------------------------------------------------------------

### Χρήση της «χιαστί ιδιότητας»


::: {style="background-color: #b5b1de; border: 2px solid #2f3e50; color: #25188a; padding: 15px; border-radius: 5px;"}

**Θεωρία και Ορισμοί**

*   **Ορισμός:** Η **χιαστί ιδιότητα** είναι ένα μαθηματικό κριτήριο που μας επιτρέπει να ελέγξουμε γρήγορα την ισοδυναμία δύο κλασμάτων.

*   **Κανόνας:** Δύο κλάσματα $\dfrac{\alpha}{\beta}$ και $\dfrac{\gamma}{\delta}$ είναι ισοδύναμα αν και μόνο αν τα **χιαστί γινόμενα** είναι ίσα: **$\alpha \cdot \delta = \beta \cdot \gamma$**.

$$\dfrac{\alpha}{\beta} = \dfrac{\gamma}{\delta} \Leftrightarrow \alpha \cdot \delta = \beta \cdot \gamma$$

**Ιδιότητες**

*   Αν τα γινόμενα δεν είναι ίσα, τότε τα κλάσματα δεν είναι ισοδύναμα.

*   Η ιδιότητα αυτή χρησιμοποιείται επίσης για την επίλυση εξισώσεων όπου αναζητείται ένας άγνωστος όρος κλάσματος.

:::

**Παραδείγματα**

1.  $\dfrac{3}{5}$ και $\dfrac{10}{14}$: $3 \cdot 14 = 42$, $5 \cdot 10 = 50$. Επειδή $42 \neq 50$, δεν είναι ισοδύναμα.
2.  $\dfrac{3}{8}$ και $\dfrac{18}{48}$: $3 \cdot 48 = 144$, $8 \cdot 18 = 144$. Είναι ίσα, άρα ισοδύναμα.
3.  $\dfrac{12}{48}$ και $\dfrac{14}{52}$: $12 \cdot 52 = 624$, $14 \cdot 48 = 672$. Δεν είναι ίσα.
4.  $\dfrac{12}{48}$ και $\dfrac{3}{12}$: $12 \cdot 12 = 144$, $3 \cdot 48 = 144$. Είναι ίσα.
5.  $\dfrac{13}{14}$ και $\dfrac{26}{28}$: $13 \cdot 28 = 364$, $14 \cdot 26 = 364$. Είναι ισοδύναμα.

**Ασκήσεις**

1.  Ελέγξτε την ισοδυναμία των $\dfrac{2}{3}$ και $\dfrac{18}{27}$.
2.  Ελέγξτε την ισοδυναμία των $\dfrac{3}{4}$ και $\dfrac{1}{2}$.
3.  Ελέγξτε την ισοδυναμία των $\dfrac{7}{8}$ και $\dfrac{30}{40}$.
4.  Ελέγξτε αν τα $\dfrac{13}{12}$ και $\dfrac{169}{144}$ είναι ισοδύναμα.
5.  Ελέγξτε αν τα $\dfrac{14}{9}$ και $\dfrac{58}{36}$ είναι ισοδύναμα.
6.  Ελέγξτε αν τα $\dfrac{84}{97}$ και $\dfrac{1176}{1358}$ είναι ισοδύναμα.
7.  Εξετάστε αν τα αεροπλάνα με πληρότητα $\dfrac{28}{32}$ και $\dfrac{98}{112}$ μεταφέρουν τον ίδιο αριθμό επιβατών.
8.  Βρείτε το $x$ αν το $\dfrac{x}{8}$ μετατραπεί σε ισοδύναμο με παρονομαστή 24.
9.  Βρείτε την τιμή του $\alpha$ ώστε $\dfrac{12}{5} = \dfrac{\alpha}{55}$.
10. Βρείτε την τιμή του $\beta$ ώστε $\dfrac{125}{55} = \dfrac{25}{\beta}$.
11. Εξετάστε την ισοδυναμία των $\dfrac{7}{5}$ και $\dfrac{84}{60}$.
12. Εξετάστε την ισοδυναμία των $\dfrac{1}{8}$ και $\dfrac{48}{528}$.




------------------------------------------------------------------------
### Ασκήσεων .... συνέχεια

**Λυμένες Ασκήσεις**

1.  **Ερώτηση:** Βρείτε ένα ισοδύναμο κλάσμα του $\dfrac{1}{2}$ με παρονομαστή το 4.

**Λύση:** Πολλαπλασιάζουμε και τους δύο όρους με το 2: $\dfrac{1 \cdot 2}{2 \cdot 2} = \dfrac{2}{4}$.

2.  **Ερώτηση:** Απλοποιήστε το κλάσμα $\dfrac{6}{15}$.

**Λύση:** Διαιρούμε και τους δύο όρους με τον ΜΚΔ τους, που είναι το 3: $\dfrac{6:3}{15:3} = \dfrac{2}{5}$.

3.  **Ερώτηση:** Είναι τα κλάσματα $\dfrac{1}{2}$ και $\dfrac{4}{8}$ ισοδύναμα;

**Λύση:** Ελέγχουμε τα χιαστί γινόμενα: $1 \cdot 8 = 8$ και $2 \cdot 4 = 8$.
Επειδή $8=8$, είναι ισοδύναμα.

4.  **Ερώτηση:** Τρέψτε το $\dfrac{3}{4}$ σε ισοδύναμο με αριθμητή 21.

**Λύση:** Επειδή $3 \cdot 7 = 21$, πολλαπλασιάζουμε και τον παρονομαστή με το 7: $4 \cdot 7 = 28$.
Άρα $\dfrac{21}{28}$.

5.  **Ερώτηση:** Το κλάσμα $\dfrac{2}{5}$ είναι ανάγωγο;

**Λύση:** Ναι, γιατί το 2 και το 5 δεν έχουν κοινό διαιρέτη εκτός από τη μονάδα.


\

**Άλυτες Ασκήσεις**

1.  Μετατρέψτε το κλάσμα $\dfrac{1}{6}$ σε ισοδύναμο με παρονομαστή 12, 30 και 60.

2.  Απλοποιήστε τα κλάσματα: $\dfrac{24}{48}, \dfrac{36}{45}, \dfrac{66}{77}$.

3.  Εξετάστε αν είναι ισοδύναμα τα ζεύγη: $\dfrac{4}{5}$ και $\dfrac{20}{25}$, $\dfrac{32}{64}$ και $\dfrac{1}{2}$.

4.  Βρείτε τον άγνωστο $x$ στην ισότητα: $\dfrac{5}{6} = \dfrac{x}{42}$.

5.  Κάντε ομώνυμα τα κλάσματα $\dfrac{5}{6}$ και $\dfrac{4}{15}$.

6.  Μετατρέψτε το $\dfrac{2}{3}$ σε ισοδύναμο με παρονομαστή 120.

7.  Απλοποιήστε το κλάσμα $\dfrac{114}{76}$ μέχρι να γίνει ανάγωγο.

8.  Βρείτε τρία ισοδύναμα κλάσματα για το $\dfrac{1}{3}$.

9.  Πώς ονομάζεται η διαδικασία με την οποία μικραίνουμε τους όρους ενός κλάσματος;

10. Συμπληρώστε την ισότητα: $\dfrac{3}{8} = \dfrac{a=  }{24}$.
